[package]
name = "attemptedProject"
version = "0.1.0"
authors = ["Admin <Admin@DESKTOP-1OMSIJ3>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
